name: Promote Snap
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      snap:
        description: Snap name to promote
        required: true
        default: testflinger-cli
        type: choice
        options:
          - testflinger-cli
      to-channel:
        description: Channel to promote to
        required: true
        default: latest/stable
        type: choice
        options:
          - latest/stable
          - latest/candidate
          - latest/beta
      from-channel:
        description: Channel to promote from
        required: true
        default: latest/beta
        type: choice
        options:
          - latest/candidate
          - latest/beta
          - latest/edge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  promote-snap:
    name: Promote Snap
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
      SNAP_NAME: ${{ inputs.snap }}
      SNAPCRAFT_TO_CHANNEL: ${{ inputs.to-channel }}
      SNAPCRAFT_FROM_CHANNEL: ${{ inputs.from-channel }}
    steps:
      - name: Validate inputs
        run: |
          echo "Snap: $SNAP_NAME"
          echo "To Channel: $SNAPCRAFT_TO_CHANNEL"
          echo "From Channel: $SNAPCRAFT_FROM_CHANNEL"
          if [ "$SNAPCRAFT_TO_CHANNEL" = "$SNAPCRAFT_FROM_CHANNEL" ]; then
            echo "Error: To channel and from channel cannot be the same."
            exit 1
          fi
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic
      - name: Promote Snap
        run: |
          snapcraft promote --yes "$SNAP_NAME" \
            --to-channel "$SNAPCRAFT_TO_CHANNEL" \
            --from-channel "$SNAPCRAFT_FROM_CHANNEL"
