name: Close Stale PRs
permissions: {}
on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/stale.yaml
  workflow_dispatch:
  schedule:
    - cron: "57 11 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  stale:
    name: Mark as Stale
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # To write comments and close PRs
      issues: write # To write comments and close issues
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          stale-pr-message: "This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in a week."
          close-pr-message: "This PR was closed because of inactivity. Feel free to re-open this once you want to work on it again!"
          stale-issue-message: "This issue is stale because it has been open for one year with no activity. Remove the stale label or comment or this will be closed in a week."
          close-issue-message: "This issue was closed because of inactivity. Feel free to re-open this if you are still encountering this!"
          days-before-stale: 60
          days-before-close: 7
          days-before-issue-stale: 360
          days-before-issue-close: 7
